exception: only clear L2C_ERR flag bits if apple_sysregs_unlocked
Writing this reg would cause another exception, leading to an endless
loop of exceptions. This way we can at least recover from some
exceptions on M4.

Signed-off-by: Yureka <yuka@yuka.dev>