exception: Fix el1_call
Save x0 in x29 (which is caller-saved, and we don't overwrite ourselves),
save CurrentEL in x29 so we can check it later, and then check x29 later
(rather than reading CurrentEL from EL1).

Signed-off-by: Alyssa Milburn <amilburn@zall.org>