exception: Don't update ELR_EL1 when taking an exception from GL1
Fixes: accb393510bc ("Add support for handling EL3.")
Signed-off-by: Sven Peter <sven@svenpeter.dev>