rust: Add workaround for rust 1.99.0 regression.
librust.a fails to link with "undefined reference to `wcslen'" caused by
LLVM 23 regression reported in [1]. Add
"-C llvm-args=-disable-loop-idiom-wcslen" to RUSTFLAGS to workaround
this bug.

Link: https://github.com/rust-lang/rust/issues/163614 [1]
Signed-off-by: Janne Grunau <j@jannau.net>