CI: rust: Downgrade rust to 1.98.1
librust.a fails to link with "undefined reference to `wcslen'" caused by
LLVM 23 regression reported in [1].

Link: https://github.com/rust-lang/rust/issues/163614 [1]
Signed-off-by: Janne Grunau <j@jannau.net>